services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8080:8080"
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "8000:80"
    #environment:
    #  - NGINX_HOST=foobar.com
    #  - NGINX_PORT=80
    depends_on:
      - api
