services:
  api:
    build:
      context: ./src/api
    container_name: api
  web:
    build:
      context: ./src/web
    container_name: web
    ports:
      - "8000:80"
    depends_on:
      - api
