services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    container_name: api
    #ports:
    #  - "8080:8080"
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    container_name: web
    #environment:
    #  - API_URI=http://apiaaaa:8080 # FIXME
    ports:
      - "8000:80"
    depends_on:
      - api
