name: CI Pipeline
on:
  workflow_dispatch: # allows manual trigger
  push:
  pull_request:
    branches: [ main ]
jobs:
  terraform-ci:
  call-tf-reusable-workflow:
    uses: atrakic/terraform-test-workflow/.github/workflows/tf-reusable-workflow.yml@main
    with:
      working_directory: tests/tf
