name: Terraform CI
on:
  workflow_dispatch: # allows manual trigger
  push:
    paths:
      - '**.tf'
      - '**.tfvars'
      - '**.hcl'
      - 'modules/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.tf'
      - '**.tfvars'
      - '**.hcl'
      - 'modules/**'
      - '.github/workflows/ci.yml'
permissions:
  security-events: write # Needed to upload-sarif
  contents: read # Needed to clone repo
  actions: read # Potentially needed for private repositories (see https://github.com/github/codeql-action/issues/2117)
jobs:
  terraform-ci:
    uses: atrakic/terraform-test-workflow/.github/workflows/tf-reusable-workflow.yml@main
    with:
      terraform_version: ">= 1.0"
      # terraform_security_test_enabled: false
