name: CI Pipeline
on:
  workflow_dispatch: # allows manual trigger
  push:
  pull_request:
    branches: [ main ]
jobs:
  terraform-ci:
    uses: atrakic/terraform-test-workflow/.github/workflows/tf-reusable-workflow.yml@main
    with:
      terraform_version: ">= 1.0"
